- name: Deploy
  hosts: all
  vars_files:
    - vars.yml
  become: yes

  tasks:
    - name: Switch branch to the specified branch
      shell: |
        git fetch origin {{ branch }}
        git switch {{ branch }}
        git pull origin {{ branch }}
      args:
        chdir: "{{ working_dir }}"

    - name: Manage MySQL service state
      ansible.builtin.systemd:
        name: mysql
        state: "{{ 'restarted' if use_mysql else 'stopped' }}"
        enabled: "{{ 'yes' if use_mysql else 'no' }}"

    - name: Manage NGINX service state
      ansible.builtin.systemd:
        name: nginx
        state: "{{ 'restarted' if use_nginx else 'stopped' }}"
        enabled: "{{ 'yes' if use_nginx else 'no' }}"

    - name: Build Go application if use_app is true
      shell: /home/isucon/local/golang/bin/go build -o {{ bin_name }}
      args:
        chdir: "{{ working_dir }}/go"
      # use_app が true の場合にのみ実行
      when: use_app | bool

    - name: Manage App service state
      ansible.builtin.systemd:
        name: "{{ app_name }}"
        state: "{{ 'restarted' if use_app else 'stopped' }}"
        enabled: "{{ 'yes' if use_app else 'no' }}"
