- name: Install New Relic
  hosts: all
  roles:
    - role: newrelic.newrelic_install
  vars_files:
    - vars.yml
  vars:
    targets:
      - infrastructure
      - logs
      - nginx
      - mysql
  environment:
    NEW_RELIC_API_KEY: "{{ new_relic_api_key }}"
    NEW_RELIC_ACCOUNT_ID: "{{ new_relic_account_id }}"
    NEW_RELIC_REGION: "{{ new_relic_region }}"
    NEW_RELIC_MYSQL_ROOT_PASSWORD: root
    NEW_RELIC_MYSQL_PASSWORD: newrelic
    NEW_RELIC_MYSQL_USERNAME: newrelic
